CREATE DATABASE ng_games_db_1;

USE ng_games_db_1;

CREATE TABLE Games(
    id INT(11) NOT NULL,
    title VARCHAR(180) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image VARCHAR(200) NOT NULL,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Games
    ADD CONSTRAINT tbl_games_id_PK PRIMARY KEY (id);

ALTER TABLE Games
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE Games
    MODIFY image VARCHAR(600) NOT NULL;

DESCRIBE Games;